# Generated by Django 5.0.1 on 2024-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_category_options_alter_images_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
