# Generated by Django 5.0.1 on 2024-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_items_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
