# Generated by Django 5.0.1 on 2024-02-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_items_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="items",
            options={"ordering": ["title"], "verbose_name_plural": "Items"},
        ),
        migrations.RenameField(
            model_name="items",
            old_name="item_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="items",
            old_name="item_price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="items",
            old_name="item_name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="items",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
