# Generated by Django 5.0.1 on 2024-02-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_alter_items_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Images",
        ),
    ]
